### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by rochelle8044** [effectai/effect-network#101]
If you click on 'Edit this page in GitHub' link at the bottom of this page: (and a few others) https://docs.effect.network/Effect-Network/about.html , it gives you this 404 error: _The 'effectai/effect-network' repository doesn't contain the 'docs/Effect-Network/dapp-ecosystem.md' path in 'master'._

**Comment by djmbritt** [comment]
Indeed, i think because the branch isn't merged with main yet. 
We either need to specify the branch or we need to merge it into main.

**Comment by laurensV** [comment]
its merged in main now
