### ISSUE TITLE
Create efxtaskproxy process

### ISSUE THREAD

**Issue by djmbritt** [effectai/effect-network#108]
## Feature
Figure out how to add a method to the sdk that will let users easily add their campaign to efxtaskproxy.

Either it is a checkbox in the campaign creation form, or programmatically in the sdk.

Probably an action needs to be created to adjust the permissions on eosio.

An alternative is to let the owner of the campaign transfer their ownership of the campaign to Effect Network's efxtaskproxy.

The problem here is that they will not be able to edit their campaigns anymore.

This feature needs to be thought out further to make sure that it is a solid process that users and devs can rely on.

## Steps

-

**Comment by jeisses** [comment]
The preferred way to achieve this is by changing the campaign owner, which is covered here: https://github.com/effectai/effect-network/issues/106

To make this feature complete we will need to update the task proxy to remember the original campaign owner and allow it to be changed back.

**Comment by jeisses** [comment]
This workflow is obsolete in V2
