### ISSUE TITLE
Implement network fees

### ISSUE THREAD

**Issue by jeisses** [effectai/effect-network#88]
## Feature

A percentage of the task rewards on the platform should be collected as a network fee.

## Description

Effect Network will implement a network fee that is collected by the DAO to sustain the development of the network.

With the mainnet release all the smart contract technology is in place to implement this in a decentralized way. The goal is to have the fees be collected  completely autonomous (so it happens automatically, no manual actions) and as real-time as possible.

The fee parameter will be an extremely important parameter for the network - as both workers and requesters will be impacted by the value.

### Technical remarks

- Effect Network operates on it's own virtual account system, which means fees are collected in vEFX, and the `feepool.efx` must have a vaccount to collect funds.
- After a task is completed on the platform there is delay before it can be paid out. This delay gives requesters time to validate a users work. This means that fee collection must also be delayed until the payout of the work
- The percentage of fees collected will be a global configuration that can be set by the DAO with a proposal
- Technically, fees will come from the user end. Example: if a user earned 1,000 EFX in a batch and clicks payout, 900 EFX is sent to the user and 100 EFX is sent to the feepool
  - We could change the user interfaces to account for the fees, so the user won't be surprised
  - We have considered swapping this, and make the requester pay the fee on task creation. But that does not play nicely as requesters should be able to cancel outstanding tasks that have not been completed.

### Steps

- Implement a configuration parameter with the global network fee and the network destination vaccount
- In the `payout` action, split the payout between the worker and the network fee
- Implement a withdraw function in the feepool that will convert the vEFX into real EFX so it gets registered as reward

**Comment by djstrikanova** [comment]
I think there will be interest at some point to allow the DAO to choose a percentage of these network fees to be burned as well. There was a proposal passed on this a while back 

https://dao.effect.network/proposals/17

**Comment by jeisses** [comment]
An alternative is to pay out the fee on `publishbatch`. Both option would probably

**Comment by jeisses** [comment]
> I think there will be interest at some point to allow the DAO to choose a percentage of these network fees to be burned as well. There was a proposal passed on this a while back
> 
> https://dao.effect.network/proposals/17

Thanks for bringing that up, we should keep this in mind.

Currently all fees are being collected to `feepool.efx` and from there they are distributed to guardians every cycle. 

This might be the right place to actually perform the burn - maybe we can use a vector of "fees" that are taken from the worker, that can be configured by the DAO.

The default value would be:
- 5% guardians
- 5% burned

The remainder of the value would always go to the worker (90% in the above case).

I also had a discussion with Laurens about taking the fees on `publishbatch` instead of `payout`. This means fees will come in quicker, and the logic is more "requester pays fees" than "worker pays fees" (example: from the task reward 100% goes to the worker; the requester would just pay on top). This also works nicer if network fees change in the future.

**Comment by laurensV** [comment]
To expand a bit on the discussion me and Jesse had: In order to do it on `publishbatch` we also have to implement an additional check to see if the batch is funded for both the fees and the costs for the tasks, but it would save quite a lot of time in the frontend adjusting for fees in worker payouts, so I prefer the `publishbatch` option. It also shows better that the fees are being paid by the requester, not the worker.

A downside to this is that if you decide to cancel your batch or not all tasks get done, you already paid the fee for all tasks in your batch (while with the `payout` option you only pay fees for tasks that are actually done), but I don't think its that big of a problem.
